fix : Gemfile.lock 강제 업데이트
An error occurred while installing sass-embedded (1.93.3), and Bundler cannot
continue.

In Gemfile:
  jekyll-theme-chirpy was resolved to 7.3.1, which depends on
    jekyll-archives was resolved to 2.3.0, which depends on
      jekyll was resolved to 4.4.1, which depends on
        jekyll-sass-converter was resolved to 3.1.0, which depends on
          sass-embedded
Error: The process '/opt/hostedtoolcache/Ruby/3.1.6/x64/bin/bundle' failed with exit code 5

배포 중 이러한 에러가 발생함